# Server port configuration
server.port=8080

# Enable H2 Console for browser access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 Database connection settings
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=vaishnavi
spring.datasource.password=221631

# JPA and Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true