name: learn-github-actions

on:
  push:
    branches: ["main" , "master"]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout Code
       uses: actions/checkout@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build with maven
        run: mvn clean install

      - name: log into docker hub
        uses: docker/login-action@v3
        with:
          username: jonnagaddalavaishnavi
          password: UeVwr2-YXUn*!iN

      - name: Build docker image
        run: docker build -t jonnagaddalavaishnavi/calc:latest

      - name: push docker image
        run: docker push jonnagaddalavaishanvi/calc:latest


